const PAGE_SIZE=48;let all=[],filtered=[],shown=0,summary;
const $=id=>document.getElementById(id);
const pct=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'n/a';

Promise.all([fetch('data/summary.json').then(r=>r.json()),fetch('data/results.json').then(r=>r.json())]).then(([s,r])=>{summary=s;all=r;renderSummary();fillFilters();applyFilters()}).catch(error=>{$('baseline').textContent=`Unable to load report data: ${error}`});

function renderSummary(){const t=summary.thorvg;$('baseline').innerHTML=`Baseline <strong>${t.version}</strong>${t.commit?` · commit <a href="${t.commit_url}"><code>${t.commit.slice(0,12)}</code></a>`:` · converter SHA-256 <code>${t.converter_sha256.slice(0,12)}</code>`}${t.dirty?' · dirty working tree':''} · generated ${summary.generated_at}`;$('suites').replaceChildren(...summary.suites.map(s=>{const e=document.createElement('article');e.className='suite';e.innerHTML=`<h3>${s.name}</h3><p>${s.track} · ${s.spec}</p><p class="rate">${pct(s.pass,s.pass+s.fail)}</p><dl><dt>Indexed</dt><dd>${s.total}</dd><dt>PASS / FAIL</dt><dd>${s.pass} / ${s.fail}</dd><dt>SKIP (unsuitable baseline)</dt><dd>${s.skip||0}</dd></dl>`;return e}))}

function fillFilters(){const values=key=>[...new Set(all.flatMap(r=>Array.isArray(r[key])?r[key]:[r[key]]).filter(Boolean))].sort();for(const [id,key] of [['suite-filter','suite'],['status-filter','status'],['element-filter','elements'],['issue-filter','issue_type']]){const select=$(id);for(const value of values(key)){const o=document.createElement('option');o.value=value;o.textContent=value;select.append(o)}select.addEventListener('change',applyFilters)}$('search').addEventListener('input',applyFilters);$('reset').addEventListener('click',()=>{for(const id of ['search','suite-filter','status-filter','element-filter','issue-filter'])$(id).value='';applyFilters()});$('more').addEventListener('click',renderMore)}

function applyFilters(){const q=$('search').value.trim().toLowerCase(),suite=$('suite-filter').value,status=$('status-filter').value,element=$('element-filter').value,issue=$('issue-filter').value;filtered=all.filter(r=>(!suite||r.suite===suite)&&(!status||r.status===status)&&(!element||r.elements.includes(element))&&(!issue||r.issue_type===issue)&&(!q||`${r.test} ${r.title} ${r.feature} ${r.elements.join(' ')}`.toLowerCase().includes(q)));shown=0;$('results').replaceChildren();$('match-count').textContent=`${filtered.length.toLocaleString()} of ${all.length.toLocaleString()} indexed files`;renderMore()}

function renderMore(){const end=Math.min(shown+PAGE_SIZE,filtered.length),fragment=document.createDocumentFragment();for(const r of filtered.slice(shown,end))fragment.append(card(r));$('results').append(fragment);shown=end;$('more').hidden=shown>=filtered.length}

function card(r){const node=$('card-template').content.firstElementChild.cloneNode(true);node.classList.add(r.status.toLowerCase());node.querySelector('.suite-name').textContent=`${r.suite} · ${r.feature}`;node.querySelector('h3').textContent=r.test;node.querySelector('.status').textContent=r.status;node.querySelector('.description').textContent=r.title;const assessment=node.querySelector('.baseline-assessment');assessment.hidden=!r.baseline_suitability;assessment.textContent=r.baseline_suitability?`Baseline ${r.baseline_suitability}: ${r.baseline_reason}`:'';node.querySelector('.tags').textContent=`Elements: ${r.elements.join(', ')||'none'} · Issue: ${r.issue_type} · Reason: ${r.reason}`;for(const [name,url] of [['reference',r.reference_image],['rendered',r.rendered_image],['diff',r.diff_image]]){node.querySelector(`.${name}`).src=url;node.querySelector(`.${name}-link`).href=url}node.querySelector('.metrics').textContent=`Visual ${r.visual_status} · changed ${(100*r.changed_ratio).toFixed(2)}% · content ${(100*r.content_changed_ratio).toFixed(2)}% · MAE ${r.mae.toFixed(3)}`;for(const cls of ['open-source','download-source'])node.querySelector(`.${cls}`).href=r.source;node.querySelector('.upstream').href=r.upstream;node.querySelector('.copy-source').addEventListener('click',async event=>{const button=event.currentTarget;try{await navigator.clipboard.writeText(await fetch(r.source).then(x=>x.text()));button.textContent='Copied'}catch{button.textContent='Copy failed'}setTimeout(()=>button.textContent='Copy SVG',1200)});return node}
